import Wrec, { css, html } from "../wrec.js";

// This code was generated by ChatGPT using the "o3 pro" model,
// and then modified.
class ToggleSwitch extends Wrec {
  static properties = {
    checked: { type: Boolean, dispatch: true },
  };

  // Toggles on mouse‑click or space/enter keys.
  toggle() {
    this.checked = !this.checked;
  }

  handleKey(e) {
    if (e.code === "Space" || e.code === "Enter") {
      e.preventDefault();
      this.toggle();
    }
  }

  static css = css`
    div {
      cursor: pointer;
      display: inline-block;
      position: relative;
      width: 44px;
      height: 26px;
      outline: none;
    }

    .track {
      position: absolute;
      inset: 0;
      background: #ccc;
      border-radius: 13px;
      transition: background 160ms;
    }

    .thumb {
      position: absolute;
      top: 2px;
      left: 2px;
      width: 22px;
      height: 22px;
      background: #fff;
      border-radius: 50%;
      box-shadow: 0 0 2px rgb(0 0 0 / 0.4);
      transition: transform 160ms;
    }

    .checked .track {
      background: #4caf50;
    }

    /* thumb slides with a CSS transition */
    .checked .thumb {
      transform: translateX(18px);
    }
  `;

  // The tabindex attribute is required to make the div focusable.
  static html = html`
    <div
      aria-checked="this.checked"
      class="this.checked ? 'checked' : ''"
      onClick="toggle"
      onKeyDown="handleKey"
      role="switch"
      tabindex="0"
    >
      <!-- The onKeyDown attribute above can be replaced by this:
           onKeyDown="this.handleKey(event)" -->
      <span class="track"></span>
      <span class="thumb"></span>
    </div>
  `;
}

ToggleSwitch.register();
