import Wrec, {css, html} from '../src/wrec.js';

class RadioGroup extends Wrec {
  static properties = {
    labels: {type: String},
    legend: {type: String},
    name: {type: String, required: true},
    values: {type: String},
    value: {type: String}
  };

  static css = css`
    :host > div {
      display: flex;
      gap: 0.5rem;
    }

    fieldset {
      border-color: var(--border-color, 'black');
      display: inline-flex;
      flex-direction: column;
      align-items: start;
      gap: 0.5rem;

      > legend {
        color: var(--legend-color, 'black');
      }

      > div {
        display: flex;
        flex-direction: var(--direction, row);
        gap: var(--gap, 1rem);
      }
    }

    input {
      margin: 0;
    }
  `;

  // wrec requires a static html property.
  // Dynamic content inside it must be generated by a JavaScript expression
  // that can use "this." to refer to the current instance.
  static html = html`
    <fieldset>
      <legend>this.legend</legend>
      <slot name="before"></slot>
      <div>this.makeButtons(this.labels, this.values)</div>
      <slot name="after"></slot>
    </fieldset>
  `;

  handleChange(event) {
    this.value = event.target.value;
  }

  makeButtons(labels, values) {
    const labelArray = labels.split(',');
    const valueArray = values.split(',').map(value => value.trim());
    // prettier-ignore
    return valueArray.map((value, index) => html`
      <div>
        <input
          type="radio"
          id=${value}
          name=${this.name}
          onchange="handleChange"
          value=${value}
          checked="this.value === '${value}'"
        />
        <label for=${value}>${labelArray[index]}</label>
      </div>
    `).join('');
  }
}

RadioGroup.register();
